version = 5.7.0
archive_dir = /etc/letsencrypt/archive/www.cattemiao.com
cert = /etc/letsencrypt/live/www.cattemiao.com/cert.pem
privkey = /etc/letsencrypt/live/www.cattemiao.com/privkey.pem
chain = /etc/letsencrypt/live/www.cattemiao.com/chain.pem
fullchain = /etc/letsencrypt/live/www.cattemiao.com/fullchain.pem
[renewalparams]
account = bff5c9e41448a5e11ac5ab69ee293545
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
[acme_renewal_info]
ari_retry_after = 2026-08-18T09:10:47
